const
  k = require('./constants.js'),
  Crunchbase = require('./scrappers/crunchbase.js'),
  Glassdoor = require('./scrappers/glassdoor.js'),
  LinkedinSalary = require('./scrappers/linkedinSalary.js'),
  LinkedinCompany = require('./scrappers/linkedinCompany.js'),
  StackShare = require('./scrappers/stackshare.js');
  
module.exports = {
  //Key(string name), the scrappers class, and the version
  SCRAPPERS: [
    [k.LINKEDIN_COMPANY, LinkedinCompany, 1],
    [k.LINKEDIN_SALARY, LinkedinSalary, 1],
    // [k.CRUNCHBASE, Crunchbase, 1],
    [k.STACKSHARE, StackShare, 1],
    [k.GLASSDOOR, Glassdoor, 1], 
  ],
  
  /////////////////////////
  //SALARY CALCULATION
  /////////////////////////
  //assume two year average tenure and discount bonuses by .9 as taxed more / speculative
  TENURE: 1.9,
  BONUS_MULTIPLER: .85 ,

  COMPANY_LIST: [
    "affirm",
    "airbnb",
    "airtable",
    "amazon",
    "apple",
    "asana",
    "aurora",
    "blend",
    "brex",
    "box",
    "clover-health",
    "cloudera",
    "coursera",
    "coinbase",
    "convoy",
    "cruise",
    "databricks",
    "docker",
    "dropbox",
    "facebook",
    "flexport",
    "figma",
    "glint",
    "google",
    "gusto",
    "instacart",
    "lemonade",
    "linkedin",
    "lyft",
    "medium",
    "microsoft",
    "nuro",
    // "neuralink",
    "palantir-technologies",
    "paypal",
    "pinterest",
    "plaid",
    "quora",
    "robinhood",
    // "rockset",
    "rubrik",
    "salesforce",
    // "samsara",
    "slack",
    "snap-inc",
    "square",
    "stripe",
    "tesla",
    "twitter",
    "two-sigma-investments",
    "uber",
    "udacity",
    "waymo",
    "treehouse",
    // "pandora",
    // "Social Capital",
    // "tile",
  ],
}